### ISSUE TITLE
Unable to resolve dependencies due to use of yandex's internal npm mirror 

### ISSUE THREAD

**Issue by micjax** [yandex-cloud/yfm-docs#123]
Hi, I was trying to build yfm with checklist, katex and emoji support, but when I ran `npm ci`, it times out as it can't fetch https://npm.yandex-team.ru/warning/-/warning-4.0.3.tgz?rbtorrent=8d20d1692a0c8284d510aa6fa832a46481a89e89 
(from`package-lock.json`)

My guess that `npm.yandex-team.ru` is an internal domain which only people from Yandex can access, so I'm unable to build yfm myself. Can you make sure that it is possible to reproduce the build without access to corporate vpn? Thanks.

**Comment by burashka** [comment]
Hi!
Yes, you are right. Internal NPM registry got into package-lock. I'm sorry. I fixed it in dependencies ([@doc-tools/transform](https://github.com/yandex-cloud/yfm-transform/pull/118) and [@doc-tools/components](https://github.com/yandex-cloud/docs-components/pull/67)) and will update @doc-tools/docs in coming soon.

**Comment by burashka** [comment]
Fixes in master. Package version: 1.18.3. Please, try.
