### ISSUE TITLE
I don't get it, where is the resulting "Leading page" htm?

### ISSUE THREAD

**Issue by Nakilon** [yandex-cloud/yfm-docs#164]
```none
$ cat yfm/toc.yaml 
---
index: yfm/index.yaml
items:
- name: ...
  href: ....md
- name: ...
  href: ....md

$ cat yfm/index.yaml 
---
links:
- title: ...
  description: ...
  href: ....md
- title: ...
  description: ...
  href: ....md
```
Now after I do `yfm -i ./yfm -o ./out -s --single-page` the `out` directory only has `_bundle` and the `html` per `md` input file, but where is the Leading page? Where is the `index.htm` or something supposed to be a root for the docs user?

P.S.: also the use of `href: index.yaml` at https://ydocs.tech/en/project/toc#structure isn't documented so I assume it's the pointer to the Leading page.

**Comment by yndx-birman** [comment]
Try to change `yfm/toc.yaml` to this
```
href: index.yaml # instead of "index: yfm/index.yaml"
items:
```

If this does not work, please let us know and also try to add the leading page as the first item.
```
href: index.yaml
items:
- name: Overview
  href: index.yaml
- name: ...
  href: ....md
```

**Comment by Nakilon** [comment]
```none
href: index.yaml # instead of "index: yfm/index.yaml"
```
This did the trick! Thanks.

**Comment by Nakilon** [comment]
@yndx-birman  у меня linkify одну ссылку не обработал -- вероятно, дело в не очень известном домене -- где про это тикет заводить?

**Comment by yndx-birman** [comment]
1.`linkify` does not process links not wrapped in link syntax, you should use [text](link) for any link
2. single-page is under development https://github.com/yandex-cloud/yfm-docs/pull/122. It requires two steps to build it right now. In the first step, a valid markdown single-page page is created using the following arguments`--single-page --output-format=md'. There are changes in the PR above that will allow you to create it in just one step.
