### ISSUE TITLE
Недостаточно информации по установке плагинов

### ISSUE THREAD

**Issue by DegaZZZ** [yandex-cloud/yfm-docs#247]
Здравствтуйте! До последнего не хотелось тут писать, так как надеялся разобраться сам, но перепробовав всё так и не смог достичь установки плагинов. Я хотел перенести свои заметки с формулами из Obsidian в HTML через ваш билдер и собственно говоря YFM, но как бы я не пытался следовать инструкции в документации нужный плагин не подрубается. Не могли бы вы чуть подробнее расписать что и как нужно делать? Заранее спасибо!

**Comment by 3y3** [comment]
Добрый день.
Давайте начнем по порядку:

Какая именно инструкция вам не помогла?

У нас есть инструкция по подключению плагинов к трансформеру, а вот про подключение к билдеру официальной инструкции нет, потому что выглядит это примерно так:
```
nvm use 14
mkdir -p docs-plugins
cd docs-plugins
echo "{}" > package.json
npm i markdown-it-emoji
echo "module.exports = { emoji: require('markdown-it-emoji') }" > index.js
cd ../

mkdir -p doctools
cd doctools
echo "{ \"scripts\": {\"start\": \"yfm\"}}" > package.json
npm i @doc-tools/docs
cp -r ../docs-plugins node_modules/@doc-tools/docs/build
```

Нормальное подключение плагинов будет имплементировано позже.

**Comment by DegaZZZ** [comment]
Спасибо ответ!
Извиняюсь, что изначальный пост был немного сумбурным.

Я говорю как раз про билдер. В [документации](https://ydocs.tech/ru/plugins/import) говорится, что просто нужно скачать плагин и перекинуть его в папку ./plugins. Ну, либо же пересобрать Билдер самостоятельно со сразу встроенными плагинами. Однако ничего из этого у меня не получилось сделать, потому и написал сюда.

Попробую сделать как вы сказали, надеюсь получится. 

Спасибо, буду ждать, YFM очень нравится своим удобным дизайном и документацию вузовским проектам да и просто как красивый рендер для MD делаю через него.

**Comment by DegaZZZ** [comment]
К сожалению не получилось, так что закрою тему, чтобы issue не мешался. Буду ждать нормального подключения плагинов. Спасибо за попытку объяснить!
