### ISSUE TITLE
Is customising documentation with a logo possible?

### ISSUE THREAD

**Issue by epogrebnyak** [yandex-cloud/yfm-docs#281]
I noticed  `yfm` package generates documentation without logo and search when building documentation locally:

![изображение](https://user-images.githubusercontent.com/9265326/215923571-b193d2f7-43a0-448a-9dee-fe5a0da1e78d.png)
 
![изображение](https://user-images.githubusercontent.com/9265326/215923400-e592f156-6cc6-4ef1-935b-3c82aff43b04.png)

Is there a possibility to add logo and search and how is this imlemented? Many thanks in advance.

**Comment by epogrebnyak** [comment]
Probably answered at https://github.com/yandex-cloud/yfm-docs/issues/151, but maybe there are any updates?

**Comment by Eugeon** [comment]
> 

Hi @epogrebnyak 
It's the same for the moment still, sorry. 
From the development perspective - we are concentrating on architecture improvements and alignment as of now. 
We know the importance of UI thus possible customization is within our roadmap, but can't commit under strict deadline.
Thank you! 

//Evgeny

**Comment by epogrebnyak** [comment]
> Hi @epogrebnyak It's the same for the moment still, sorry. From the development perspective - we are concentrating on architecture improvements and alignment as of now. We know the importance of UI thus possible customization is within our roadmap, but can't commit under strict deadline. Thank you!

Makes sense to make architecture a priority! Glad you you have UI customization on roadmap as well, would definitely help broader use of yfm-docs.
